language: ruby
rvm:
 - 2.2
 - jruby

services:
  - postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

  test:
  adapter: postgresql
  database: travis_ci_test

#If your local test setup uses different credentials or settings to access the
#local test database, we recommend putting these settings in a database.yml.travis
#in your repository and copying that over as part of your build:

# adding the below to this .travis.yml file

#before_script:
#  - cp config/database.yml.travis config/database.yml
